USE dawn;
DROP TABLE IF EXISTS `plan`;
CREATE TABLE `plan` (
  `ID` INT(7) NOT NULL AUTO_INCREMENT,
  `TITLE` TEXT NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `IMAGE` TEXT NULL,
  `CREATERID` INT NOT NULL,
  PRIMARY KEY (`ID`)
);