CREATE TABLE ADDRESS(
	`ID`          INT NOT NULL AUTO_INCREMENT,
	`AREA`    INT NOT NULL,
	`PREFECTURE`       INT NOT NULL,
	`CITY`    INT NOT NULL,
	`NAME`         TEXT NOT NULL,
    PRIMARY KEY(`ID`)
);