CREATE TABLE `USER` (
	`ID`          INT NOT NULL AUTO_INCREMENT,
	`USERNAME`    VARCHAR(64) NOT NULL UNIQUE,
	`EMAIL`       VARCHAR(128) NOT NULL UNIQUE,
	`PASSWORD`    TEXT NOT NULL,
	`DISPLAYNAME` TEXT NOT NULL,
	`DATEOFBIRTH` DATE NOT NULL,
	`SEX`         TEXT NOT NULL,
    PRIMARY KEY(`ID`)
);

CREATE TABLE `CONTACTS` (
	`ID`        INT NOT NULL AUTO_INCREMENT,
	`USERID`    INT NOT NULL UNIQUE,
	`HOMEPAGE`  TEXT NULL,
	`INSTAGRAM` TEXT NULL,
	`TWITTER`   TEXT NULL,
	`FACEBOOK`  TEXT NULL,
	`TIKTOK`    TEXT NULL,
	`BIOGRAPHY` TEXT NULL,
    PRIMARY KEY(`ID`),
	FOREIGN KEY `FK_USERID`(`USERID`) REFERENCES `USER`(`ID`)
);

CREATE TABLE `JOB` (
	`ID`             INT  NOT NULL AUTO_INCREMENT,
	`USERID`         INT  NOT NULL UNIQUE,
	`JOBNAME`        TEXT NOT NULL,
	`DATEOFFIRSTJOB` DATE NOT NULL,
    PRIMARY KEY(`ID`),
	FOREIGN KEY `FK_USERID`(`USERID`) REFERENCES `USER`(`ID`)
);

CREATE TABLE `CREATOR`(
	`ID`       INT NOT NULL AUTO_INCREMENT, 
	`USERID`   INT  NULL UNIQUE,
	`REALNAME` TEXT NULL,
    PRIMARY KEY(`ID`),
	FOREIGN KEY `FK_USERID`(`USERID`) REFERENCES `USER`(`ID`)
);