on:
  push:

name: CI/CD (Push)

jobs: 
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup docker
        run: docker-compose up
        working-directory: ./docker_compose
