on:
  push:

name: CI/CD (Push)

jobs: 
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
        id: go
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go- 
      - name: setup docker
        run: docker-compose up -d
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: test
        run: ./validate-test.sh
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ISSUER: ${{ secrets.ISSUER }}
          IS_TEST: ${{ secrets.IS_TEST }}
